helm chart add image pull secrets
mailgun/gubernator pull request #141
Opened 2022-05-06 03:31 UTC by maxmeng-oss

2022-05-09 13:57 UTC, Baliedge commented
@maxmeng-oss Thank you for the contribution.  Could you please write up a story in the PR around this change?  Since we don't use Helm internally, it would be helpful to know what the context and requirements are around this change.

2022-05-11 03:48 UTC, maxmeng-oss commented
> @maxmeng-oss Thank you for the contribution. Could you please write up a story in the PR around this change? Since we don't use Helm internally, it would be helpful to know what the context and requirements are around this change.

Done, please take a look, thanks.

2022-05-11 13:23 UTC, Baliedge requested changes

2022-05-11 13:23 UTC, Baliedge commented on deploy/helm/templates/deployment.yaml
> +      {{- with $.Values.gubernator.image.pullSecrets }}
Additionally, the option of setting this value must be documented.  I'd like to see a commented out example usage in `deploy/helm/templates/deployment.yaml`.

2022-05-17 13:15 UTC, merged