Add environment variable to set minimum TLS version on server tls config
mailgun/gubernator pull request #160
Opened 2022-12-02 21:37 UTC by denkyl08

This will allow folks to block usage of TLS 1.0 and TLS1.1 which have known vulnerabilities.

2022-12-05 14:22 UTC, Baliedge requested changes
I like this security-minded update.  Just a small behavioral change I recommended.  Thanks for the contribution!

2022-12-05 14:22 UTC, Baliedge commented on config.go
> +		return tls.VersionTLS10
The default ought to be the most secure option, 1.3.

2022-12-06 19:58 UTC, Baliedge requested changes
Code looks great.  Just get the checks to pass and I'll merge.

2022-12-07 19:07 UTC, denkyl08 commented
@Baliedge  I am not able to reproduce the test failure locally. Could you re-run these jobs? Also, I'm not sure why the first job  was cancelled, do you know?

2022-12-08 01:11 UTC, Baliedge approved these changes
That turned out to be a pre-existing test issue that'll need to be investigated later.  Approved.

2022-12-08 01:12 UTC, merged