Now respects gubernator.CacheSize config option
mailgun/gubernator pull request #180
Opened 2023-06-19 19:06 UTC by thrawn01

### Purpose
#179 Reported the `config.CacheSize` argument was ignored. This PR updates `NewGubernatorPool()` to pass in the `workers` and `cacheSize` via the `config` option instead of method arguments.

### Implementation
* Renaming `concurrency` and `pool` to `workers` where possible.
* Fixed issue with cluster.Start() where bind port was not assigned or reported correctly
* `go vet ./...` no longer complains that `main()` is defined twice in `/cmd/gubernator` moved healthcheck into `/cmd/healthcheck`

2023-06-20 14:13 UTC, Baliedge approved these changes

2023-06-20 16:38 UTC, MatthewEdge commented on cluster/cluster.go
> +	var peers []gubernator.PeerInfo
I think we should leave the original `make()` version to avoid a chunk of allocations

2023-06-20 16:44 UTC, MatthewEdge requested changes

2023-06-21 19:01 UTC, MatthewEdge approved these changes

2023-06-21 19:05 UTC, merged